Delete the "self" when call "_set_degraded" function
Which will raise Exception:
TypeError: 'LoadBalancerPluginv2' object does not
support item assignment.

Change-Id: Ic3f653468c7cec8cc0434d3df9b42cc1660f9260
Closes-Bug: #1607585
(cherry picked from commit b09d4d2ee0ea71a52679f0eb2743116dbb7e5442)